### ISSUE TITLE
Feature request: change files/folders

### ISSUE THREAD

**Issue by gipo355** [MagicDuck/grug-far.nvim#103]
Hey!

Thanks for your plugin, I'm finding it very pleasant to use

Recently I've found myself needing to bulk rename files and folders and looking for solutions I ended up using Yazi.

I've searched how to do it with quick fix after adding a list from telescope to no avail.

I immediately thought bulk rename of files and folders would be a very good feature missing in the neovim plugin ecosystem to my knowledge.

Do you think it could be possible to implement it in grug-far?

**Comment by MagicDuck** [comment]
hmm, that's an interesting use case, although I don't think it's appropriate for grug-far as this plugin is `ripgrep` based and also philosophically since it would be doing too many things.

I believe this might be something for a plugin like `oil.nvim` to handle.
Alternatively, you can do something like this suggestion:
https://www.reddit.com/r/vim/comments/w0i2ow/comment/igef0q3/

**Comment by gipo355** [comment]
Thank you for the suggestion!
