### ISSUE TITLE
Configure title?

### ISSUE THREAD

**Issue by LandonSchropp** [MagicDuck/grug-far.nvim#105]
Is there a way to configure the buffer title for grug-far? I'd love for mine to say `Find and Replace` and not include the search string. 🙂

**Comment by MagicDuck** [comment]
The philosophy with grug-far is that you would potentially be able to have the results of multiple searches around that you could refer back to, i.e. you are not limited to one search. If you set a fixed name for the search buffer, you will only be able to have one of them since nvim does not allow multiple buffers with the same name.

I do understand though that different people have different ways of using it, so I think this feature would work best together with the "toggling feature" you requested in https://github.com/MagicDuck/grug-far.nvim/issues/106
That is, you would be "toggling" on/off a particularly named grug-far buffer.

To clarify on the toggling part, by toggling off I am assuming you mean just hiding the buffer? Or do you mean killing it.

**Comment by MagicDuck** [comment]
Had a bit of time today to work on this and I think just hiding the buffer makes the more sense. If necessary we can add an option to clear it each time you toggle it on.

This is how you use it:
https://github.com/MagicDuck/grug-far.nvim?tab=readme-ov-file#toggle-visibility-or-a-particular-instance-and-set-title-to-a-fixed-string

Lemme know if that works for you!

**Comment by LandonSchropp** [comment]
@MagicDuck Apologies, I was on vacation and I'm just now getting back to things.

The experience I'm trying to emulate is how find/replace works in editors like VSCode, Atom, Sublime, etc. In these examples, the find/replace a panel that can be opened up on the side or bottom of the window, used, and then closed again. There's never more than one find/replace panel, because it's not part of the same tab interface as the rest of the application.

The closest comparison in the Neovim world be how [Neotree](https://github.com/nvim-neo-tree/neo-tree.nvim) works. I can call `:Neotree toggle` to open the panel if it's not already open, and close it if it is. Neotree does not interfere with other buffers I might have open, and does some magic with its split to ensure that it always works as expected.

Of course, as you mentioned, this is all personal preference, and I'm very happy regardless. 🙂

**Comment by LandonSchropp** [comment]
Your solution looks exactly like what I'm looking for! I'll test it out tomorrow to make sure everything works okay. Thank you!

**Comment by LandonSchropp** [comment]
That worked perfectly! Thanks @MagicDuck. 🙌

**Comment by MagicDuck** [comment]
Awesome, glad to hear! 😃
