### ISSUE TITLE
Multiline Replacements - Preserve line terminators

### ISSUE THREAD

**Issue by scottmckendry** [MagicDuck/grug-far.nvim#132]
Now I'm fairly certain this is just skill issues on my part, so I'm hoping for some direction. I can search for `\r\n` patterns with the `--multiline` flag but when I use them in the replace field it just replaces with the literal string `\r\n`. Is there a simple way to preserve newlines using grug-far? 

I came across [this issue in the ripgrep repo](https://github.com/BurntSushi/ripgrep/issues/2025) that poses a solution, but my grugbrain can't figure out how to translate it for this plugin (I think because Windows ANSI escapes are different?)

Appreciate any guidance 🙂

**Comment by MagicDuck** [comment]
hi @scottmckendry , you can't use `\r\n` directly since they would be interpreted literally as the command is not executed through a shell. What you can do instead is place them in a character class and use the `--multiline` flag. Here is an example. I am not on windows so I converted a file to dos line endings and the grug buffer has those `^M` things in it, but you get the idea:
<img width="2364" alt="image" src="https://github.com/user-attachments/assets/c3dc588e-a7c9-40e4-bd7b-13a643f0fca5">

**Comment by MagicDuck** [comment]
actually, with `--multiline`, `\s*` is sufficient to match 😄 
<img width="748" alt="image" src="https://github.com/user-attachments/assets/92a7b90f-a771-490f-ad41-c9efe85dc494">

**Comment by MagicDuck** [comment]
ah doh, I should have read that more carefully, you are asking about replace...

**Comment by MagicDuck** [comment]
I was able to do it using a capture group:
<img width="1972" alt="image" src="https://github.com/user-attachments/assets/fc3b4fb0-1548-4c53-801d-0c12b5789d5f">

**Comment by scottmckendry** [comment]
Perfect! Just what I was after 🙂 
Thanks so much.

**Comment by MagicDuck** [comment]
great! 😄
