### ISSUE TITLE
question: is it possible to operate outside of the current working directory?

### ISSUE THREAD

**Issue by mikavilpas** [MagicDuck/grug-far.nvim#146]
Hi, thanks for the awesome plugin! I included it as the recommended search and replace integration in my plugin https://github.com/mikavilpas/yazi.nvim/pull/250 today.

I was wondering if it's supported to filter files outside of the current working directory. Here's an example of what I get:

![image](https://github.com/user-attachments/assets/fe40e751-760a-4f93-a0c4-b442c11f62dc)

To make that a bit clearer, `vim.uv.cwd()` points to `/Users/mikavilpas/git/yazi.nvim` while my Files Filter points to `/Users/mikavilpas/.config/nvim/lua/config/**`

I'm wondering if I have forgotten to set some value, or if this is simply not supported. I can maybe prevent confusing cases like this in my integration.

Thanks!

**Comment by MagicDuck** [comment]
@mikavilpas that's awesome. I have it in my neovim config todos to try yazi.nvim someday and this integration makes even more enticing 😆 

Regarding operating within a specific directory, different from cwd, that is supported by passing the directory path in `Flags`. `Files Filter` gets passed as an argument to `--glob`, so that's likely why it's not working.

<img width="1259" alt="image" src="https://github.com/user-attachments/assets/7a3d86fc-bbbb-40c3-9d3a-4370008cc18e">

I've been wondering if the messaging / UI around this could be improved, so let me know if you have any ideas 😄 
Maybe this would be good?
<img width="894" alt="image" src="https://github.com/user-attachments/assets/180b5365-3aaf-4570-a94b-47cc3d4c2256">

**Comment by MagicDuck** [comment]
actually, this might be better:
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/b4a1d21c-2c29-4982-a38d-3e0b69028244">

**Comment by MagicDuck** [comment]
just FYI, I've noticed a bug on invalid paths that I'll be looking into:
https://github.com/MagicDuck/grug-far.nvim/issues/148

**Comment by MagicDuck** [comment]
I've that change to the default placeholders to make it more clear that a dir / file path can go in `Flags` 😄 
https://github.com/MagicDuck/grug-far.nvim/pull/149

**Comment by mikavilpas** [comment]
It seems to work perfectly now! I only switched the `Flags` to the `Files Filter` field and all is good now 😄 

Thanks so much for the help!

**Comment by MagicDuck** [comment]
Awesome, great to hear!
