### ISSUE TITLE
ast-grep integration

### ISSUE THREAD

**Issue by divaltor** [MagicDuck/grug-far.nvim#173]
Thanks for this awesome plugin.

Is it possible to integrate [ast-grep](https://github.com/ast-grep/ast-grep) as optional replacement for `ripgrep`?

**Comment by MagicDuck** [comment]
Looks like a very cool tool, but would be quite a significant amount of work to properly integrate.

Something like this would have to happen:
1. create a new "backend" abstraction and move all `rg` related stuff behind it. This is mostly the code that calls rg and parses tokens for the matches and files from the output here:  https://github.com/MagicDuck/grug-far.nvim/tree/main/lua/grug-far/rg
But there are also some bits of code that check for `--multiline` replaces and prevent `sync all` action in those cases. All that would have to go behind calls like `backend:supportsMultilineSync(opts)` or the like, depending on what makes sense.
2. Implement new "backend" for `ast-grep`. I did a little bit of looking around and it seems like unlike `rg` it supports doing the actual replace and also you can use `--json` flag to get results in json form (rg also has that but there was an issue with it in that it would not work properly with --replace), so hopefully would be much easier to get the parsed output to pass to the results list renderer.
Things like single line sync might have to be disabled for it though as from what I see it always seems to work across lines.  
4. add an option to pick a backend when launching, `rg or ast-grep` to opts.lua
5. `Files Filter` input might not make sense for `ast-grep` so might need to be removed in that case (unless we re-purpose it for the --lang prop?).
6. Modify test infrastructure to fetch a particular version of `ast-grep` for usage in tests
7. Write tests for it

So not saying no, but we need a hero to step forward and do it 😄 ...

**Comment by MagicDuck** [comment]
Moved `rg` behind a new "engine" abstraction layer.
So technically what's left is:
1. Implement an engine for `ast-grep`, which basically means implementing this interface:
```lua
---@class GrugFarEngine
---@field type GrugFarEngineType
---@field search fun(params: EngineSearchParams): (abort: fun()?, effectiveArgs: string[]?) performs search
---@field replace fun(params: EngineReplaceParams): (abort: fun()?) performs replace
---@field sync fun(params: EngineSyncParams): (abort: fun()?) syncs given changes to their originating files
---@field getInputPrefillsForVisualSelection fun(initialPrefills: GrugFarPrefills): GrugFarPrefills gets prefills updated with visual selection searchand any additional flags that are necessary (for example --fixed-strings for rg)
```
I am not sure if `ast-grep` can support `sync` action at all as ast-grep is multiline by definition and sync is line based. 
2.  update history management so that history entries include an `Engine:` field, and we switch to that engine when history entry is picked
3.  add an action to toggle engine? not sure, might be helpful
4. display the engine name somewhere in the UI so there is no confusion
5. make `options.placeholders` support function values, where the function would get the engine type as a parameter and return the right placeholder string
6. `Files Filter` input might not make sense for ast-grep so might need to be removed in that case (unless we re-purpose it for the --lang prop?). If we remove it, adding entries to history / getting them would have to be updated.
7. modify test infrastructure to fetch a particular version of ast-grep for usage in tests
8. add tests for it in a separate directory and run them in a separate github action

**Comment by MagicDuck** [comment]
Will look into slowly implementing it since it’s a fun technical challenge. No promises though…
Consider me successfully nerd sniped, lol

**Comment by MagicDuck** [comment]
I got sucked in and ended up finishing it in a fit of madness 😆 

@divaltor let me know what you think, you can use it with option `engine='astgrep'`, or by switching to `astgrep` engine at runtime with the `Swap Engine` action (`<localleader>e`).

<img width="1264" alt="image" src="https://github.com/user-attachments/assets/84eab994-0dbc-46c7-a779-1b3f6c41b9d0">

**Comment by divaltor** [comment]
> I got sucked in and ended up finishing it in a fit of madness 😆
> 
> @divaltor let me know what you think, you can use it with option `engine='astgrep'`, or by switching to `astgrep` engine at runtime with the `Swap Engine` action (`<localleader>e`).
> <img alt="image" width="1264" src="https://private-user-images.githubusercontent.com/95201/355255292-84eab994-0dbc-46c7-a779-1b3f6c41b9d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDkyNTcsIm5iZiI6MTcyMzEwODk1NywicGF0aCI6Ii85NTIwMS8zNTUyNTUyOTItODRlYWI5OTQtMGRiYy00NmM3LWE3NzktMWIzZjZjNDFiOWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA5MjIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhOTg3NWMyYTA4N2NiYzVjNzVmMjRjMGNlODRhMjRlZWIxYTJhNGQxMGU0YjIyOWZiY2NmOTNiM2IyY2RmYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NXCN18z-tzrq2jZP1SbDoJiWqCOymUMYrvoXicP0RxE">

It works very well, excellent work, thanks ❤️
