### ISSUE TITLE
Feature - preview

### ISSUE THREAD

**Issue by niba** [MagicDuck/grug-far.nvim#196]
I would like to propose a new feature called preview.

Very often, when I do search & replace in my projects, I want to quickly skim through the results to double-check everything. In vscode, when you perform a search and replace and select one of the results, you get a diff view of the entire file.
![image](https://github.com/user-attachments/assets/b4097554-9d3a-4d28-8859-25b9452abac6)

It would be really nice to have something similar here (if that's possible). 

Workflow:
1. Perform a search.
2. Go to one of the results.
3. Automatically display the diff on selection (as an option) or use a special keybinding/command.
   a) preview / diff shouldn't clutter your existing buffers.

**Comment by MagicDuck** [comment]
I think an external tool with git is probably much better for this kind of review.
Just apply the replace and then use lazygit or whatever tool to review it. If you don't like it, you can just discard and try again. Seems like an easier process. You just have to make sure to commit your previous work...

Alternatively, if what we really want is to show inline diffs that's maybe something that could be implemented, although a bit of a pain with ripgrep since we would have to call it twice (once without the replacement and once with). Note that you can already specify the `--context=<num>` flag to see more context around each match.

If use the `astgrep` engine it will show you diffs already:

![image](https://github.com/user-attachments/assets/21275505-5db4-41c0-b5b8-2378cae8e66b)

Although context is broken for it temporarily. See: https://github.com/ast-grep/ast-grep/issues/1381#issuecomment-2271707710

**Comment by MagicDuck** [comment]
Unfortunately inline diff can not work with rg atm, see https://github.com/BurntSushi/ripgrep/issues/1872
And I dont think the side by side diff is a good fit for this plugin. As such I will close this.

**Comment by niba** [comment]
@MagicDuck thanks for digging into this topic.

The trick with Git is indeed something that could replace what I mentioned. I just need to get into the habit of committing everything before any serious renaming 😄

**Comment by MagicDuck** [comment]
Yeah, or even just staging would be sufficient.
The way I do it is I have a special keybind in my terminal that takes me to a tab containing lazygit (and back I am on the lazygit tab). I stage every time I am in a good spot and am going to do some refactoring or something slightly destructive 😆

**Comment by MagicDuck** [comment]
@niba FYI, we now show a diff for replace. Here's an example with 2 lines of context (-C 2):
<img width="1256" alt="image" src="https://github.com/user-attachments/assets/fdd2079f-085a-49c0-b56d-44e5e86fd660">

**Comment by niba** [comment]
Amazing! Thanks for letting me know
