### ISSUE TITLE
`File does not haver editied row anymore` error

### ISSUE THREAD

**Issue by Jaehaks** [MagicDuck/grug-far.nvim#219]
Thank you for your efforts, 

I got this error `File does not haver editied row anymore` when I change some word in some files
But in other files grug-far works properly.
![image](https://github.com/user-attachments/assets/95b97d62-7065-493f-bd2c-7775da65f872)

Could I know what is the reason?

**Comment by MagicDuck** [comment]
Hi @Jaehaks, that error message is output when the file you are syncing to has been changed externally and does not contain the row you made your change on anymore.

So for example, let's say you have a file `foo.txt` containing:
```
1 hello
2 world
3 of things!
```
where 1, 2, 3 are the line numbers. If you change say line 2 `world` -> `planet` in the grug-far results, but before syncing edit `foo.txt` so everything is on one line:
```
1 hello world of things!
```
you will get this error since line 2 does not exist in the file anymore. 
This can happen sometimes if you do git operations, etc. in between.

**Comment by MagicDuck** [comment]
I've made a change to slightly improve the error message so it's hopefully less confusing.

**Comment by MagicDuck** [comment]
Closing for issue management purposes. Please reopen if you see any problems!
