### ISSUE TITLE
Allow to customize floating window settings

### ISSUE THREAD

**Issue by lervag** [MagicDuck/grug-far.nvim#299]
I've started to test grug-far and so far I like it well. It may end up replacing ctrlsf.vim for me! So thanks for making this!

Now, one minor issue for me is that I want to change the border of the floating help window which is created here:

https://github.com/MagicDuck/grug-far.nvim/blob/190c03d54e8976491e6e49acb97087bf4182b079/lua/grug-far/actions/help.lua#L76-L86

I would be very happy if you could implement a possibility for customizing the floating window config. I could attempt to make a PR for it myself; the code seems well written and relatively easy to follow.

**Comment by MagicDuck** [comment]
Hi there! Glad you like grug-far and thanks for the compliment on the code :)
Sure, am totally fine with adding such options, probably best under a “helpWindow” grouping (helpWindow.border, etc). Note that if you desire uniformity in borders you might want to doa similar thing for the history window. Feel free to submit a PR, otherwise I will randomly get to it whenever I get some free time…

**Comment by lervag** [comment]
I made a quick attempt at addressing this now; please see #300.

**Comment by MagicDuck** [comment]
closing this now, thanks for your work on this @lervag ! 😄

**Comment by lervag** [comment]
No problem; glad to contribute!
