### ISSUE TITLE
Deleting replacement options from buffer not working?

### ISSUE THREAD

**Issue by lcpichette** [MagicDuck/grug-far.nvim#315]
Preface: Graphically this plugin is stunning. The contributors, particularly MagicDuck, have done an incredible job with this plugin. I'm really grateful for, what really is, a kind of christmas gift for my neovim flow. Brown-nosing aside, here's my request/bug report:

Context: I was on the look for a way to confirm individual replaces, or remove them from the list. 

https://github.com/MagicDuck/grug-far.nvim/issues/24 Seems to address exactly this!

However, I found a few visual things that made it confusing to me. The "Sync" vs "Replace" logic seems cryptic, and without knowing the inner-workings of the plugin I'm inclined to avoid "sync" as I'm not sure what it does.

### Sync line not removing/moving result from diff buffer when accepted
https://github.com/user-attachments/assets/c0c07dfb-b7a9-469b-8c55-8cb36ee6af4f

Suggested result:
1. Move accepted result(s) to separate Grug-Far "Accepted Changes" buffer after `,l` or `,r` actions are executed. 
2. Remove accepted result from diff buffer. Undo in file would add result back to diff buffer. I think this option is more intuitive and would take less effort, but I could see an argument that keeping track of a list of change you've made is useful.

### Deleting items from buffer doesn't actually impact replace functionality
https://github.com/user-attachments/assets/3d5c25d2-fbba-4bef-9f1f-61327a826307

Suggested result:
1. Prevent deletes from diff buffer
2. Make it clearer as to what that action does (or maybe I just missed it in the README? Apologies if so)
4. Make deletes in diff buffer impact replace command (this I think makes the most sense)

**Comment by MagicDuck** [comment]
thank you for the kind words and the well written issue, @lcpichette! 😄 

Replies to above:
I'll try to fill you in on the history so we can arrive at some sort of solution together.

**Sync line not removing/moving result from diff buffer when accepted**

So this is an issue that arises due to the history of the Sync Line feature. Initially, this plugin did not have "diffs", just lines with the matches highlighted, similar to running `rg` from the command line. Sync Line was originally intended to be used by doing search without replace string, inline editing some of the results and syncing them back. It also coincidentally worked in the replace case since there was no diff thing and we could show the little indicator on the side, see screenshot:

<img width="752" alt="image" src="https://github.com/user-attachments/assets/834de69b-eda0-456a-8dcb-d0e9aa4bca85">
 
With the diff in place now, we cannot show that little indicator anymore, so we need to find another way to show sync.
If we chose to remove the synced match, the tricky part is that it's not actually trivial to say whether removing it is correct. For example, let's say you added a bit of extra text at the end of the "replacement text line". Technically, it should still show up in the results buffer, since it would still be matched by the search term. Ex:

<img width="637" alt="image" src="https://github.com/user-attachments/assets/888c075e-4fb0-43df-a9dd-df4aefefcda9">

So I am not sure 100% how to proceed ... 
Some ideas I have are:
1. update the before/after lines to the same (synced) value and use a different nerdfont icon instead of the diff indicators  
2. maybe we add an option to the effect of "remove line on sync line", if people prefer that behaviour. This is your "Suggested result option 2" from above

Note: related issue: https://github.com/MagicDuck/grug-far.nvim/issues/313 

**Deleting items from buffer doesn't actually impact replace functionality**

This is on purpose and is documented here: https://github.com/MagicDuck/grug-far.nvim?tab=readme-ov-file#syncing-results-lines-back-to-originating-files

The relevant part is:
```
If you don't edit the results list, Sync All and Replace have equivalent outcomes, except for one case. When you do multi-line replace with `--multiline` and `--multiline-dot-all` flags, sync won't work so you have to use replace. Essentially the difference it that Replace runs `rg --replace=... --passthrough` on each file and does not depend at all on what's in the results area. Sync All does a line by line sync based on what's in the results area.
```
In addition to that, one extra difference is that there is a maximum limit on the number of matches shown in the results buffer (  maxSearchMatches = 2000), so if that is exceeded, replace will still work as per normal, but sync will only affect the results in the buffer. 

> Suggested result:

> 1. Prevent deletes from diff buffer

This would be against grug-far philosophy. It tries to limit edits as little as possible. You can just undo if you screw something up.

> 2. Make it clearer as to what that action does (or maybe I just missed it in the README? Apologies if so)

It's documented like I mentioned, but maybe could be improved? Let me know if you have any ideas!

> 3. Make deletes in diff buffer impact replace command (this I think makes the most sense)

`Sync All` already does that. If you delete some matches, they will be ignored when syncing.

**Comment by lcpichette** [comment]
All of this provides a great amount of context. I really appreciate the effort you put in to catch me up and explain to me the situation.

You know what's best for this project, all I can provide is my opinion as someone who loves the tool. 

I now understand, enough at least -- I think, the context and historical changes that have led this project to the functionality that currently exists. That being said, I'm going to just put out my perspective and you can do with it what you will : )

1. Having deletes in diff buffer working for `sync all` but not `sync line` is inconsistent and confusing. Again, how it currently functions totally makes sense given the history of the plugin : ) But that perspective still remains.
2. Changing the default behavior of some action(s) is generally bad. Those who update the plugin might find themselves confused as to why it's not behaving as it once did. Not to say it's always bad, just generally best to avoid imho. This is not what you're proposing, but a note that's relevant for my later suggestions.
3. Sync vs Replace syntax is still confusing. Not confusing given the context and history of the plugin, but for those who don't know of it (like myself in the beginning) it was just confusing. 

My proposal (perhaps unrealistic, but idealistic):
----
Keep sync line and sync all functionalities Knowing that they literally sync the files means that their names make sense. 

What I'm wanting is a new replace action it seems. "Replace next result" (`,R`?). This would run `,r` but just for the top-most result in the diff buffer.

I would think that by default `,R` should open a confirmation modal as well. It might also be useful to allow the user to disable this confirmation modal if they want to, maybe with something like `:lua require('grug-far').open({ confirmBeforeReplace = false })`?

This confirmation modal would have the following options (c/n/N/y/Y):

_Modal Options_
- c: Cancel/escape the action
- n: Does not make any change and removes the result from buffer.
- N: Does not make any change and removes the result from buffer. Also runs `,R` again.
- y: Accepts change and removes result from buffer. 
- Y: Accepts change and removes result from buffer. Also runs `,R` again.

- After some thinking: I don't think there should be file-specific dropping/accepting. I think it would congest the UI and filters already cover this.

_Lifecycle_
- action-on-destroy: Before this action is to be completed (c/n/N/y/Y modal not yet shown), diff between resultOriginFile:# and gf-buffer:# w/o replace changes. Is there a difference? If so, then (in your example) THINGS was added and a modal should appear warning the user that there were changes made beyond what's proposed in the "replace" field. A simple y/n to acknowledge this or cancel the action. It might be useful to if there's an option and/or flag to disable this check.

This means at-most we have two modals. One for if there's non-replace text-change that was made within the diff-buffer that they haven't yet synced to the file. The next is a confirmation modal for the result replacement.
----

Again, this is from the perspective of someone who hasn't gotten their hands stuck in the cogs of this plugin -- I don't know its development pain points, and I don't know what's practical for the future of this plugin.

But this is just what I think I would enjoy using : )

I'd love to help and make a PR for this functionality (or similar), but I've never made a Neovim plugin before, and I'd feel as though I was doing a disservice to your time and this plugin by trying to hack together something that kind of works and kind of doesn't. Unrelated, but if you have any tips for getting started with making/contributing-to neovim plugins I'd really appreciate it!!

**Comment by MagicDuck** [comment]
> Having deletes in diff buffer working for sync all but not sync line is inconsistent and confusing.

Not sure what you mean by that. Sync Line only affects the current line, so deletes would not affect it by definition, right?

> Sync vs Replace syntax is still confusing. 

Yeah I know it can be slightly confusing initially, especially since people don't read the docs 😆. I just don't think there is something better right now ... maybe somebody will come along with a better suggestion.

> My proposal (perhaps unrealistic, but idealistic):

Not to deter from your vision, but have you considered the following alternative workflow?
1. enter search/replace terms
2. press <down>/<up> arrow in normal mode to navigate through the matches and preview them one by one, deleting what you don't want
3. when you are happy, press `,s` (Sync All)

I think it wins in terms of keeping things as "buffer-editing"-like as possible. 

> I'd love to help and make a PR for this functionality (or similar), but I've never made a Neovim plugin before...

Personally, I would not use this feature because  it would feel too "stateful". Like you can't stop in the middle and do something else it seems. I prefer the "sync all" approach. That being said, I understand people work in different ways and am not against somebody else adding it as an "action".

If you would like to contribute, all you have to have is willpower, time and desire to learn 😆 . Don't worry about putting in bad code, I won't let you on the code review, haha.
To get started, just clone this repo locally and then update your nvim config to load the plugin from the local dir. Ex if you are using lazy:
```
  {
    dir = '~/repos/grug-far.nvim',
    name = 'grug-far',
    config = function()
      require('grug-far').setup()
   end
 }
```

You can then make changes and they will show up when you re-launch nvim.
For instance, `nvim -c GrugFar` can be a nice helper as it runs grug far immediately upon launch.

This is an approach that will work when contributing to any plugin. You can also set up debugging through DAP, but I never got that fancy myself.

Here's an example of a simpler "action":
https://github.com/MagicDuck/grug-far.nvim/blob/55333ff5eef5f6d03828b4c52a25c7b505c4d19c/lua/grug-far/actions/gotoLocation.lua#L39

> making ... plugins

When I got started with this plugin, I just used a template like https://github.com/m00qek/plugin-template.nvim/tree/main
But if you really want quality, eventually you will want to add tests, linting, type checking and CI.

**Comment by lcpichette** [comment]
> 1. Having deletes in diff buffer working for sync all but not sync line is inconsistent and confusing.

Was just typed incorrectly. I established the confusing behavior in the description of the PR. 

Your suggested workflow makes sense. I suppose it would be `}` for next result and then `3dd` to remove it (assuming not multiline) and then `,s` to submit changes for a total of (1-4 * n) + 2 keystrokes, whereas mine would be `,R` and then possibly `y/n` plus `c/n/N/y/Y` for 2 + (1-2 * n) keystrokes. 

I think I'll give creating this as a new action a try in my off-time, mostly for the sake of learning, and in the interim use your suggested workflow -- as it's really quite sensible already.

I really appreciate the tips and resources on getting started with plugin creation and modification!

**Comment by MagicDuck** [comment]
Yes, you can also just use `d}` to delete if you want even less keystrokes 😄

**Comment by MagicDuck** [comment]
hi @lcpichette ,
FYI, I added two new actions to support incremental syncing of changes with removal from buffer. Seems a few people wanted something like that, might be closer to what you wanted as well 😄.

```
   - Apply Next <,j>                     Apply change at current line, remove it from buffer and move cursor to next change
   - Apply Prev <,k>                     Apply change at current line, remove it from buffer and move cursor to prev change
```
