### ISSUE TITLE
`replace cannot work due to missing search/replacement inputs!

### ISSUE THREAD

**Issue by teto** [MagicDuck/grug-far.nvim#37]
I tried to replace lines containing test_folder with nothing, aka remove the line, by putting nothing in the "Replace" filter but I hit:
 `replace cannot work due to missing search/replacement inputs!`
 
My search filter `.*test_folder.*\n` and with `--multiline` as a rg option 
 Is there a way to work around this ?

**Comment by MagicDuck** [comment]
hmm, this is an interesting one since we use `Replace=<empty string>` to signify that we are only conducting a search...
I need to think a bit about it.

**Comment by MagicDuck** [comment]
Addressed in https://github.com/MagicDuck/grug-far.nvim/pull/38

@teto:
Note: When replacing matches with the empty string, you will be prompted to confirm, as the change is not visible in the results list due to UI considering it just a search when there replace string is empty. If you would like to see the actual replacement in the results area, add `--replace=` to the flags.

Let me know if you see any issues
