### ISSUE TITLE
Question: what's the difference between r (replace) and s (sync all)?

### ISSUE THREAD

**Issue by Integralist** [MagicDuck/grug-far.nvim#82]
👋🏻 

Excellent plugin by the way. Really slick and good user experience 👍🏻 Thank you for building this!

Quick question (as per the title): it seems like `<leader>r` replaces all instances, but that sounds a lot like `<leader>s` (sync all). What am I missing?

**Comment by MagicDuck** [comment]
Thank you! Am happy you are enjoying the plugin! 😄 

You are correct that replace and sync are exactly the same if you don't edit the results list, except for one case. When you do multi-line replace `--multiline` and `--multiline-dot-all` flags, sync won't work so you have to use replace.

Maybe we could update the README.md to mention that at some point, haha

**Comment by Integralist** [comment]
Yeah that's would be good 👍 

Thanks for clarifying!

**Comment by MagicDuck** [comment]
hi @GitMurf 

1. yes
2. It is mentioned here: https://github.com/MagicDuck/grug-far.nvim?tab=readme-ov-file#syncing-results-lines-back-to-originating-files , but if you feel like it can be improved, I am more than happy to accept a PR :). Documentation is definitely an area that could be improved. I think it's outgrown the README.md somewhat and something similar to kuala's docs would be good (https://kulala.mwco.app/docs/usage), but am daunted by the amount of work it would be to do that, haha
3. no, I think that would be difficult to implement and would not really provide much utility since you can just use `Sync` if you want that kind of behaviour

**Comment by GitMurf** [comment]
@MagicDuck thanks for the quick response! I will think about how the readme could be clearer.
