### ISSUE TITLE
Misc issues

### ISSUE THREAD

**Issue by wustho** [MagicDuck/grug-far.nvim#85]
First of all, I really appreciated this feature: https://github.com/MagicDuck/grug-far.nvim/issues/76

But found another issues that feel like essential to some people workflow
- when using: `  windowCreationCommand = 'botright split'`, grug-far creating a empty buffer `[No Name]` poluting buflist
- when quitting with `:q` grug far buffer is not removed and poluting buflist
- somehow no autocmd event `FileType` fired with grug-far, tried `au FileType grug-far set colorcolumn=` with no luck

**Comment by MagicDuck** [comment]
hi there,

> when using:   windowCreationCommand = 'botright split', grug-far creating a empty buffer [No Name] poluting buflist

I don't see that happening ... if you have any other file open and then open grug-far, that is. If you already have a `[No Name]` buffer from something like `tabnew`, then yes, but that is normal vim behaviour since you created it...

>  when quitting with :q grug far buffer is not removed and poluting buflist
:q closes windows, not buffers. If you want to close the buffer, you should be doing either the builtin close command, `<localleader>c` by default, or just `:bd`. There are many situations where people want to close the window containing grug-far to gain real estate, but want to keep the grug-far search available to switch back to.

> somehow no autocmd event FileType fired with grug-far, tried au FileType grug-far set colorcolumn= with no luck
This works for me:
```lua
vim.api.nvim_create_autocmd('FileType', {
  group = augroup('test'),
  pattern = { 'grug-far' },
  callback = function()
    print('hello from grug-far')
  end,
})
```
Maybe try the lua version? Not sure...

**Comment by MagicDuck** [comment]
for the first issue, maybe you were seeing this one?
https://github.com/MagicDuck/grug-far.nvim/issues/83
try latest if yes...

**Comment by wustho** [comment]
Ah thank you, man, really love this plugin, indeed less mental overhead than spectre!

**Comment by MagicDuck** [comment]
no worries, btw, if you use tabnew and see leftover unnmamed buffers, you might want to use `tabnew %` for your command:

https://github.com/MagicDuck/grug-far.nvim/issues/83#issuecomment-2156173937
